spring.application.name=iot-project-web-service
server.port=8085
spring.datasource.url=jdbc:postgresql://localhost:5433/iotdb
spring.datasource.username=postgres
#spring.datasource.password=Pow3r2024C@ts
spring.datasource.password=root